application:
  port: 8080
  host: 0.0.0.0
  origins:
    - "http://localhost:3000"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "TestDB"
  require_ssl: false
