application:
  port: 8080
  host: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "backend"
  require_ssl: false
redis:
  host: "127.0.0.1"
